export const GENRES = [
    'EDM', 
    'Jazz', 
    'House Music', 
    'Country', 
    'Rock', 
    'HipHop', 
    'Reggae',
    'Rap R&B',
    'Kpop',
    'Latin',
    'Top 40',
    'Dub Step',
    'Art',
    'Gaming',
    'Food',
    'Afro Beats',
    'Pop',
    'Karaoke',
    'Throwbacks',
]